// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TF_NET_2026_IAC_Bend.Db;

#nullable disable

namespace TF_NET_2026_IAC_Bend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260615134105_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TF_NET_2026_IAC_Bend.Db.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/product1.jpg",
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/product2.jpg",
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/product3.jpg",
                            Name = "Product 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
